import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "doc",
      id: "api-reference/noxivo-engine-api",
    },
    {
      type: "category",
      label: "Messages",
      items: [
        {
          type: "doc",
          id: "api-reference/post-api-v-1-messages-send",
          label: "Send a Message",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Chats",
      items: [
        {
          type: "doc",
          id: "api-reference/get-api-v-1-chats",
          label: "GET /api/v1/chats",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Sessions",
      items: [
        {
          type: "doc",
          id: "api-reference/post-api-v-1-sessions-bootstrap",
          label: "Bootstrap Session",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/get-api-v-1-sessions",
          label: "GET /api/v1/sessions",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/get-api-v-1-sessions-by-tenant",
          label: "GET /api/v1/sessions/by-tenant",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/post-api-v-1-sessions-start",
          label: "POST /api/v1/sessions/start",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/post-api-v-1-sessions-stop",
          label: "POST /api/v1/sessions/stop",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/post-api-v-1-sessions-restart",
          label: "POST /api/v1/sessions/restart",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/post-api-v-1-sessions-logout",
          label: "POST /api/v1/sessions/logout",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Events",
      items: [
        {
          type: "doc",
          id: "api-reference/get-api-v-1-events-stream",
          label: "GET /api/v1/events/stream",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Admin",
      items: [
        {
          type: "doc",
          id: "api-reference/get-api-v-1-admin-me",
          label: "GET /api/v1/admin/me",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/post-api-v-1-admin-logout",
          label: "POST /api/v1/admin/logout",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/get-api-v-1-admin-messaging-spec",
          label: "GET /api/v1/admin/messaging/spec",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/post-api-v-1-admin-messaging-request",
          label: "POST /api/v1/admin/messaging/request",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/get-api-v-1-admin-sessions",
          label: "GET /api/v1/admin/sessions",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/post-api-v-1-admin-sessions-id-start",
          label: "POST /api/v1/admin/sessions/{id}/start",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/post-api-v-1-admin-sessions-id-stop",
          label: "POST /api/v1/admin/sessions/{id}/stop",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/post-api-v-1-admin-sessions-id-logout",
          label: "POST /api/v1/admin/sessions/{id}/logout",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/get-api-v-1-admin-sessions-id-status",
          label: "GET /api/v1/admin/sessions/{id}/status",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/get-api-v-1-admin-sessions-id-qr",
          label: "GET /api/v1/admin/sessions/{id}/qr",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/post-api-v-1-admin-sessions-bootstrap",
          label: "POST /api/v1/admin/sessions/bootstrap",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/get-api-v-1-admin-workers-status",
          label: "GET /api/v1/admin/workers/status",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/get-api-v-1-admin-events-stream",
          label: "GET /api/v1/admin/events/stream",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/post-api-v-1-admin-login",
          label: "POST /api/v1/admin/login",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/post-api-v-1-admin-register",
          label: "POST /api/v1/admin/register",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/patch-api-v-1-admin-users-id-approve",
          label: "PATCH /api/v1/admin/users/{id}/approve",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api-reference/get-api-v-1-admin-users-pending",
          label: "GET /api/v1/admin/users/pending",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Dashboard Registry",
      items: [
        {
          type: "doc",
          id: "api-reference/post-v-1-internal-dashboard-register",
          label: "POST /v1/internal/dashboard/register",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/get-v-1-internal-dashboard-config",
          label: "GET /v1/internal/dashboard/config",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/patch-v-1-internal-dashboard-config",
          label: "PATCH /v1/internal/dashboard/config",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api-reference/get-v-1-internal-dashboard-agencies",
          label: "GET /v1/internal/dashboard/agencies",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Admin - Dashboards",
      items: [
        {
          type: "doc",
          id: "api-reference/get-api-v-1-admin-dashboards",
          label: "GET /api/v1/admin/dashboards",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/get-api-v-1-admin-dashboards-agency-id",
          label: "GET /api/v1/admin/dashboards/{agencyId}",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/get-api-v-1-admin-dashboards-agency-id-sessions",
          label: "GET /api/v1/admin/dashboards/{agencyId}/sessions",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/post-api-v-1-admin-dashboards-agency-id-sync",
          label: "POST /api/v1/admin/dashboards/{agencyId}/sync",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/post-api-v-1-admin-dashboards-agency-id-suspend",
          label: "POST /api/v1/admin/dashboards/{agencyId}/suspend",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/post-api-v-1-admin-dashboards-agency-id-activate",
          label: "POST /api/v1/admin/dashboards/{agencyId}/activate",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Workers",
      items: [
        {
          type: "doc",
          id: "api-reference/get-api-v-1-workers-status",
          label: "GET /api/v1/workers/status",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Pairing",
      items: [
        {
          type: "doc",
          id: "api-reference/get-api-v-1-sessions-id-qr",
          label: "GET /api/v1/sessions/{id}/qr",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/get-api-v-1-sessions-id-status",
          label: "GET /api/v1/sessions/{id}/status",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Profile",
      items: [
        {
          type: "doc",
          id: "api-reference/get-api-v-1-sessions-id-profile",
          label: "GET /api/v1/sessions/{id}/profile",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Contacts",
      items: [
        {
          type: "doc",
          id: "api-reference/get-api-v-1-sessions-id-contacts",
          label: "GET /api/v1/sessions/{id}/contacts",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Media",
      items: [
        {
          type: "doc",
          id: "api-reference/post-api-v-1-media-send",
          label: "POST /api/v1/media/send",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Observability",
      items: [
        {
          type: "doc",
          id: "api-reference/get-api-v-1-health-messaging",
          label: "GET /api/v1/health/messaging",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Status",
      items: [
        {
          type: "doc",
          id: "api-reference/get-api-v-1-sessions-id-status-stories",
          label: "GET /api/v1/sessions/{id}/status/stories",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/post-api-v-1-sessions-id-status-text",
          label: "POST /api/v1/sessions/{id}/status/text",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Storage",
      items: [
        {
          type: "doc",
          id: "api-reference/get-api-v-1-storage",
          label: "GET /api/v1/storage",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Api Keys",
      items: [
        {
          type: "doc",
          id: "api-reference/get-api-v-1-keys",
          label: "GET /api/v1/keys",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/get-api-v-1-api-keys-me",
          label: "GET /api/v1/api-keys/me",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/post-api-v-1-api-keys-me",
          label: "POST /api/v1/api-keys/me",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/delete-api-v-1-api-keys-me",
          label: "DELETE /api/v1/api-keys/me",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "MessagingProvider Proxy",
      items: [
        {
          type: "doc",
          id: "api-reference/get-api-v-1",
          label: "GET /api/v1/{*}",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "AI Sales Agent",
      items: [
        {
          type: "doc",
          id: "api-reference/post-ai-sales-agent-state",
          label: "POST /ai-sales-agent/state",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/put-ai-sales-agent-state",
          label: "PUT /ai-sales-agent/state",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api-reference/post-ai-sales-agent-persona",
          label: "POST /ai-sales-agent/persona",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/put-ai-sales-agent-persona",
          label: "PUT /ai-sales-agent/persona",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "UNTAGGED",
      items: [
        {
          type: "doc",
          id: "api-reference/get-admin",
          label: "GET /admin",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/post-api-v-1-spa-bookings",
          label: "POST /api/v1/spa/bookings",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/get-api-v-1-spa-catalog-services",
          label: "GET /api/v1/spa/catalog/services",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/post-api-v-1-spa-auth-sign-up",
          label: "POST /api/v1/spa/auth/sign-up",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/post-api-v-1-spa-auth-sign-in",
          label: "POST /api/v1/spa/auth/sign-in",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/post-api-v-1-spa-auth-sign-out",
          label: "POST /api/v1/spa/auth/sign-out",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/get-api-v-1-spa-auth-me",
          label: "GET /api/v1/spa/auth/me",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/get-api-v-1-spa-account-bookings",
          label: "GET /api/v1/spa/account/bookings",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/get-api-v-1-spa-account-profile",
          label: "GET /api/v1/spa/account/profile",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/put-api-v-1-spa-account-profile",
          label: "PUT /api/v1/spa/account/profile",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api-reference/get-api-v-1-spa-admin-customers",
          label: "GET /api/v1/spa/admin/customers",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/get-api-v-1-spa-admin-services",
          label: "GET /api/v1/spa/admin/services",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/post-api-v-1-spa-admin-services",
          label: "POST /api/v1/spa/admin/services",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/put-api-v-1-spa-admin-site-settings",
          label: "PUT /api/v1/spa/admin/site-settings",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api-reference/get-api-v-1-spa-admin-site-settings",
          label: "GET /api/v1/spa/admin/site-settings",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/post-api-v-1-spa-admin-gallery",
          label: "POST /api/v1/spa/admin/gallery",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/get-api-v-1-spa-admin-gallery",
          label: "GET /api/v1/spa/admin/gallery",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/put-api-v-1-spa-admin-ai-concierge",
          label: "PUT /api/v1/spa/admin/ai-concierge",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api-reference/get-api-v-1-spa-admin-ai-concierge",
          label: "GET /api/v1/spa/admin/ai-concierge",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/get-api-v-1-agency-webhooks",
          label: "GET /api/v1/agency/webhooks",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/post-api-v-1-agency-webhooks",
          label: "POST /api/v1/agency/webhooks",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/put-api-v-1-agency-webhooks-webhook-id",
          label: "PUT /api/v1/agency/webhooks/{webhookId}",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api-reference/delete-api-v-1-agency-webhooks-webhook-id",
          label: "DELETE /api/v1/agency/webhooks/{webhookId}",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-reference/get-api-v-1-agencies",
          label: "GET /api/v1/agencies/",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/post-api-v-1-agencies",
          label: "POST /api/v1/agencies/",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/get-api-v-1-agencies-agency-id",
          label: "GET /api/v1/agencies/{agencyId}",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/patch-api-v-1-agencies-agency-id",
          label: "PATCH /api/v1/agencies/{agencyId}",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api-reference/get-api-v-1-agencies-agency-id-tenants",
          label: "GET /api/v1/agencies/{agencyId}/tenants",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/post-api-v-1-agencies-agency-id-tenants",
          label: "POST /api/v1/agencies/{agencyId}/tenants",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/get-api-v-1-agencies-agency-id-tenants-tenant-id",
          label: "GET /api/v1/agencies/{agencyId}/tenants/{tenantId}",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/get-api-v-1-agencies-agency-id-team",
          label: "GET /api/v1/agencies/{agencyId}/team",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/patch-api-v-1-agencies-agency-id-team-user-id",
          label: "PATCH /api/v1/agencies/{agencyId}/team/{userId}",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api-reference/delete-api-v-1-agencies-agency-id-team-user-id",
          label: "DELETE /api/v1/agencies/{agencyId}/team/{userId}",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-reference/get-api-v-1-agencies-agency-id-invitations",
          label: "GET /api/v1/agencies/{agencyId}/invitations",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/post-api-v-1-agencies-agency-id-invitations",
          label: "POST /api/v1/agencies/{agencyId}/invitations",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/patch-api-v-1-agencies-agency-id-invitations-invitation-id",
          label: "PATCH /api/v1/agencies/{agencyId}/invitations/{invitationId}",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api-reference/delete-api-v-1-agencies-agency-id-invitations-invitation-id",
          label: "DELETE /api/v1/agencies/{agencyId}/invitations/{invitationId}",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-reference/get-api-v-1-catalog",
          label: "GET /api/v1/catalog/",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/post-api-v-1-catalog",
          label: "POST /api/v1/catalog/",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/get-api-v-1-catalog-id",
          label: "GET /api/v1/catalog/{id}",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/patch-api-v-1-catalog-id",
          label: "PATCH /api/v1/catalog/{id}",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api-reference/delete-api-v-1-catalog-id",
          label: "DELETE /api/v1/catalog/{id}",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-reference/get-api-v-1-catalog-settings",
          label: "GET /api/v1/catalog/settings",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/post-api-v-1-catalog-settings",
          label: "POST /api/v1/catalog/settings",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/post-api-v-1-catalog-upload",
          label: "POST /api/v1/catalog/upload",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/post-api-v-1-catalog-ai-help",
          label: "POST /api/v1/catalog/ai-help",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/post-api-v-1-catalog-publish",
          label: "POST /api/v1/catalog/publish",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/get-api-v-1-workflows",
          label: "GET /api/v1/workflows/",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/post-api-v-1-workflows",
          label: "POST /api/v1/workflows/",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/post-api-v-1-workflows-clone",
          label: "POST /api/v1/workflows/clone",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/get-api-v-1-workflows-workflow-id",
          label: "GET /api/v1/workflows/{workflowId}",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/patch-api-v-1-workflows-workflow-id",
          label: "PATCH /api/v1/workflows/{workflowId}",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api-reference/delete-api-v-1-workflows-workflow-id",
          label: "DELETE /api/v1/workflows/{workflowId}",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-reference/post-api-v-1-workflows-workflow-id-toggle",
          label: "POST /api/v1/workflows/{workflowId}/toggle",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/get-api-v-1-workflows-workflow-id-runs",
          label: "GET /api/v1/workflows/{workflowId}/runs",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/get-api-v-1-workflows-workflow-id-analytics",
          label: "GET /api/v1/workflows/{workflowId}/analytics",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/get-api-v-1-workflows-workflow-id-execution-events",
          label: "GET /api/v1/workflows/{workflowId}/execution-events",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/get-api-v-1-team-inbox",
          label: "GET /api/v1/team-inbox/",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/get-api-v-1-team-inbox-events",
          label: "GET /api/v1/team-inbox/events",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/get-api-v-1-team-inbox-stats",
          label: "GET /api/v1/team-inbox/stats",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/get-api-v-1-team-inbox-plugins",
          label: "GET /api/v1/team-inbox/plugins",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/post-api-v-1-team-inbox-plugins",
          label: "POST /api/v1/team-inbox/plugins",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/get-api-v-1-team-inbox-billing",
          label: "GET /api/v1/team-inbox/billing",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/get-api-v-1-team-inbox-leads",
          label: "GET /api/v1/team-inbox/leads",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/post-api-v-1-team-inbox-conversation-id-assign",
          label: "POST /api/v1/team-inbox/{conversationId}/assign",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/post-api-v-1-team-inbox-conversation-id-read",
          label: "POST /api/v1/team-inbox/{conversationId}/read",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/post-api-v-1-team-inbox-conversation-id-actions",
          label: "POST /api/v1/team-inbox/{conversationId}/actions",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/post-api-v-1-team-inbox-conversation-id-unhandoff",
          label: "POST /api/v1/team-inbox/{conversationId}/unhandoff",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/post-api-v-1-team-inbox-conversation-id-suggest-reply",
          label: "POST /api/v1/team-inbox/{conversationId}/suggest-reply",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/get-api-v-1-team-inbox-conversation-id-lead",
          label: "GET /api/v1/team-inbox/{conversationId}/lead",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/post-api-v-1-team-inbox-conversation-id-lead",
          label: "POST /api/v1/team-inbox/{conversationId}/lead",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/delete-api-v-1-team-inbox-conversation-id-lead",
          label: "DELETE /api/v1/team-inbox/{conversationId}/lead",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-reference/get-api-v-1-team-inbox-conversation-id-messages",
          label: "GET /api/v1/team-inbox/{conversationId}/messages",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/post-api-v-1-team-inbox-conversation-id-messages",
          label: "POST /api/v1/team-inbox/{conversationId}/messages",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/post-api-v-1-team-inbox-conversation-id-messages-message-id",
          label: "POST /api/v1/team-inbox/{conversationId}/messages/{messageId}",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/get-api-v-1-team-inbox-conversation-id-delivery-history",
          label: "GET /api/v1/team-inbox/{conversationId}/delivery-history",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/get-api-v-1-team-inbox-conversation-id-crm",
          label: "GET /api/v1/team-inbox/{conversationId}/crm",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/patch-api-v-1-team-inbox-conversation-id-crm",
          label: "PATCH /api/v1/team-inbox/{conversationId}/crm",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api-reference/post-api-v-1-team-inbox-conversation-id-messages-message-id-actions",
          label: "POST /api/v1/team-inbox/{conversationId}/messages/{messageId}/actions",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/get-api-v-1-settings-credentials",
          label: "GET /api/v1/settings/credentials",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/post-api-v-1-settings-credentials",
          label: "POST /api/v1/settings/credentials",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/get-api-v-1-settings-shop",
          label: "GET /api/v1/settings/shop",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/post-api-v-1-settings-shop",
          label: "POST /api/v1/settings/shop",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/get-api-v-1-settings-storage",
          label: "GET /api/v1/settings/storage",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/put-api-v-1-settings-storage",
          label: "PUT /api/v1/settings/storage",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api-reference/get-api-v-1-settings-webhook-inbox-activation",
          label: "GET /api/v1/settings/webhook-inbox-activation",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/post-api-v-1-settings-webhook-inbox-activation",
          label: "POST /api/v1/settings/webhook-inbox-activation",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/delete-api-v-1-settings-webhook-inbox-activation",
          label: "DELETE /api/v1/settings/webhook-inbox-activation",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-reference/get-api-v-1-settings-webhook-inbox-sources",
          label: "GET /api/v1/settings/webhook-inbox-sources",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/post-api-v-1-settings-webhook-inbox-sources",
          label: "POST /api/v1/settings/webhook-inbox-sources",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/patch-api-v-1-settings-webhook-inbox-sources-source-id",
          label: "PATCH /api/v1/settings/webhook-inbox-sources/{sourceId}",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api-reference/get-api-v-1-settings-developer-api",
          label: "GET /api/v1/settings/developer-api",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/post-api-v-1-settings-developer-api",
          label: "POST /api/v1/settings/developer-api",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/delete-api-v-1-settings-developer-api",
          label: "DELETE /api/v1/settings/developer-api",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-reference/get-api-v-1-settings-whatsapp-check",
          label: "GET /api/v1/settings/whatsapp-check",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/get-api-v-1-settings-qr",
          label: "GET /api/v1/settings/qr",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/post-api-v-1-settings-qr",
          label: "POST /api/v1/settings/qr",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/delete-api-v-1-settings-qr",
          label: "DELETE /api/v1/settings/qr",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-reference/post-v-1-internal-inbox-conversations-conversation-id-messages",
          label: "POST /v1/internal/inbox/conversations/{conversationId}/messages",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/post-v-1-internal-inbox-sync",
          label: "POST /v1/internal/inbox/sync",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/get-v-1-internal-crm-conversations-conversation-id-profile",
          label: "GET /v1/internal/crm/conversations/{conversationId}/profile",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/patch-v-1-internal-crm-conversations-conversation-id-profile",
          label: "PATCH /v1/internal/crm/conversations/{conversationId}/profile",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api-reference/post-v-1-webhooks-messaging",
          label: "POST /v1/webhooks/messaging",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/post-v-1-messaging-session-bootstrap",
          label: "POST /v1/messaging/session/bootstrap",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/get-v-1-messaging-session-qr",
          label: "GET /v1/messaging/session/qr",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/get-v-1-messaging-session-status",
          label: "GET /v1/messaging/session/status",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/get-v-1-messaging-session-name",
          label: "GET /v1/messaging/{sessionName}/{*}",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/post-v-1-messaging-session-name",
          label: "POST /v1/messaging/{sessionName}/{*}",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/get-v-1-inbox-chats",
          label: "GET /v1/inbox/chats",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/get-v-1-inbox-conversations-conversation-id-messages",
          label: "GET /v1/inbox/conversations/{conversationId}/messages",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/post-v-1-inbox-conversations-conversation-id-messages",
          label: "POST /v1/inbox/conversations/{conversationId}/messages",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/get-v-1-inbox-messages-message-id-status",
          label: "GET /v1/inbox/messages/{messageId}/status",
          className: "api-method get",
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
