import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
import apiSidebar from "./docs/api-reference/sidebar";

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: 'Introduction',
    },
    {
      type: 'category',
      label: 'Architecture',
      items: [
        {
          type: 'autogenerated',
          dirName: 'architecture',
        },
      ],
    },
    {
      type: 'category',
      label: 'API Reference',
      items: apiSidebar,
    },
    {
      type: 'category',
      label: 'Integrations',
      items: [
        {
          type: 'autogenerated',
          dirName: 'integrations',
        },
      ],
    },
  ],
};

export default sidebars;
